name: daiku
version: '0.1.0.0'
category: Web
author: John Ky
maintainer: newhoggy@example.com
copyright: 2017-2018 John Ky
license: BSD3
github: haskell-works/daiku
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules: []
  dependencies:
  - aeson
  - amazonka
  - amazonka-core
  - amazonka-dynamodb
  - amazonka-dynamodb-streams
  - amazonka-kinesis
  - amazonka-s3
  - amazonka-sns
  - amazonka-sqs
  - base >=4.7 && <5
  - BoundedChan
  - bytestring
  - conduit
  - containers
  - directory
  - lens
  - optparse-applicative
  - raw-strings-qq
  - shake
  - text
  - yaml
executables:
  daiku-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - daiku
    - directory
    - optparse-applicative
    - shake
tests:
  daiku-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - daiku
